#ifndef _DFG_H_
#define _DFG_H_
#include "icfg.h"
#include "otf_pta.h"

using namespace std;

using DFGNode = CFGNode;
using DFGEdge = CFGEdge;
class DFG : public GenericGraph<DFGNode, DFGEdge>
{
public:
    typedef set<llvm::Value*> ValueSet;
    typedef map<DFGNode*, ValueSet> DFASet;

    DFG(ICFG& icfg, OTFPTA& pta) : icfg(&icfg), pta(&pta)
    {
        llvmParser = icfg.getLLVMParser ();
    }
    ~DFG() = default;

    void build() 
    {
        // 1. intra-procedural DFA
        for (auto itr = icfg->cfg_begin (); itr != icfg->cfg_end (); itr++)
        {
            CFG* cfg = itr->second;
            performDFA (cfg);
        }

        // 2. inter-procedural DFA
        buildIDFG();

        // 3. handle globals
        // skip here
    }

    ICFG* getICFG() { return icfg; }
private:
    LLVM* llvmParser;
    ICFG *icfg;
    OTFPTA *pta;
    map<llvm::Value*, set<DFGNode*>> defToNode;

private:
    /*
    * ============================================================
    * DFG::initializeGEN() — Pseudocode Guidance
    * ============================================================
    *
    * Goal:
    *   Build the GEN set for each CFG node.
    *
    *   GEN is represented as a DFASet:
    *     DFASet = map<DFGNode*, ValueSet>
    *
    *   For each node n, GEN[n] stores the set of definitions
    *   generated at that node.
    *
    * ------------------------------------------------------------
    * Step 0: Create an empty DFASet
    *   Initialize an empty map:
    *     GEN
    *
    * ------------------------------------------------------------
    * Step 1: Visit every CFG node
    *   Iterate through all nodes in the given CFG.
    *
    *   For each node n:
    *     - get the DFGNode* from the CFG iterator
    *
    * ------------------------------------------------------------
    * Step 2: Compute the definitions generated by the node
    *   Use the helper:
    *     getDefinitions(n)
    *
    *   This returns the ValueSet of definitions produced by n.
    *
    *   In the current framework, getDefinitions() already handles:
    *     - formal-argument definitions at function-entry nodes
    *     - explicit instruction-level definitions
    *     - implicit memory definitions introduced by store instructions
    *
    * ------------------------------------------------------------
    * Step 3: Store the result into GEN
    *   Assign:
    *     GEN[n] = getDefinitions(n)
    *
    *   This means:
    *     the definitions generated at node n are recorded
    *     as the GEN fact for that node.
    *
    * ------------------------------------------------------------
    * Step 4: Return the completed GEN set
    *   After all nodes have been processed:
    *     return GEN
    *
    * ------------------------------------------------------------
    * Output of this function:
    *   - A DFASet mapping each CFG node to its generated definitions.
    *
    * Common mistakes to avoid:
    *   - Forgetting that GEN is a DFASet, not a single ValueSet
    *   - Skipping some CFG nodes during iteration
    *   - Recomputing definitions manually instead of reusing getDefinitions()
    *   - Forgetting that getDefinitions() may also update auxiliary mappings
    *     such as defToNode for later DFG construction
    */
    inline DFASet initializeGEN (CFG *cfg)
    {
        
    }

    /*
    * ============================================================
    * DFG::initializeKILL() — Pseudocode Guidance
    * ============================================================
    *
    * Goal:
    *   Build the KILL set for each CFG node.
    *
    *   KILL is represented as a DFASet:
    *     DFASet = map<DFGNode*, ValueSet>
    *
    *   For each node n, KILL[n] stores the set of definitions
    *   that are killed (overwritten) by the definitions generated at n.
    *
    * ------------------------------------------------------------
    * Key idea:
    *   If node n defines some value v, then other definitions of the
    *   same value v in the same CFG are killed by n.
    *
    *   In this simplified implementation:
    *     - compare GEN[n] against GEN of all other nodes
    *     - if both contain the same value v, then v is killed at n
    *     - except when v is an alloca-based memory object
    *
    * ------------------------------------------------------------
    * Step 0: Create an empty DFASet
    *   Initialize:
    *     KILL
    *
    * ------------------------------------------------------------
    * Step 1: Visit every CFG node as the current node
    *   Iterate through all nodes in the CFG.
    *
    *   For each node n:
    *     - get its generated definitions:
    *         nodeGEN = GEN[n]
    *
    * ------------------------------------------------------------
    * Step 2: Skip nodes that generate no definitions
    *   If GEN[n] is empty:
    *     - there is nothing to kill
    *     - continue to the next node
    *
    * ------------------------------------------------------------
    * Step 3: Compare node n against all other CFG nodes
    *   Iterate through all nodes again:
    *     for each other node m in CFG
    *
    *   Skip the case where:
    *     m == n
    *   because a node should not compare against itself.
    *
    * ------------------------------------------------------------
    * Step 4: Inspect the definitions generated by the other node
    *   Let:
    *     otherGEN = GEN[m]
    *
    *   For each value v in otherGEN:
    *     - check whether nodeGEN also contains v
    *
    *   If yes, then n redefines the same value v that was also
    *   defined somewhere else.
    *
    * ------------------------------------------------------------
    * Step 5: Add killed definitions into KILL[n]
    *   If:
    *     v is in nodeGEN
    *   and
    *     v is NOT an llvm::AllocaInst
    *
    *   Then:
    *     insert v into KILL[n]
    *
    *   Meaning:
    *     the definition of v from another node is killed by node n.
    *
    * ------------------------------------------------------------
    * Step 6: Why skip AllocaInst?
    *   In this simplified model, alloca is treated as being bound
    *   to its memory object, so it is not killed like ordinary
    *   redefinitions.
    *
    * ------------------------------------------------------------
    * Step 7: Return the completed KILL set
    *   After all nodes have been processed:
    *     return KILL
    *
    * ------------------------------------------------------------
    * Output of this function:
    *   - A DFASet mapping each CFG node to the set of definitions
    *     killed by that node.
    *
    * Common mistakes to avoid:
    *   - Forgetting that KILL is a DFASet, not a single ValueSet
    *   - Comparing a node with itself
    *   - Adding kills for nodes with empty GEN sets
    *   - Forgetting to exclude llvm::AllocaInst values
    *   - Mixing up "generated at this node" with "killed by this node"
    */
    inline DFASet initializeKILL (CFG *cfg, DFASet& GEN)
    {
        
    }

    inline DFASet initializeSET (CFG *cfg)
    {
        DFASet dfaSet;
        for (auto itNode = cfg->begin (); itNode != cfg->end (); itNode++) 
        {
            DFGNode* node = itNode->second;
            dfaSet[node] = ValueSet();
        }

        return dfaSet;
    }

    /*
    * ============================================================
    * DFG::performDFA() — Pseudocode Guidance
    * ============================================================
    *
    * Goal:
    *   Run an intra-procedural forward reaching-definitions analysis
    *   on one CFG, compute IN and OUT sets for each node, and then
    *   use the final IN facts to build DFG edges.
    *
    *   In this implementation:
    *     - IN, OUT, GEN, and KILL are all represented as DFASet
    *     - each DFASet maps a CFG node to its corresponding ValueSet
    *
    * ------------------------------------------------------------
    * Step 0: Initialize the four data-flow sets
    *   Create:
    *     IN   = initializeSET(cfg)
    *     OUT  = initializeSET(cfg)
    *     GEN  = initializeGEN(cfg)
    *     KILL = initializeKILL(cfg, GEN)
    *
    *   Meaning:
    *     GEN[n]  = definitions generated at node n
    *     KILL[n] = definitions killed by node n
    *     IN[n]   = reaching definitions before node n
    *     OUT[n]  = reaching definitions after node n
    *
    * ------------------------------------------------------------
    * Step 1: Create a worklist for iterative propagation
    *   Use:
    *     - a queue worklist
    *     - a visited set
    *
    *   Start from the entry node of the CFG:
    *     entry = cfg->getEntryNode()
    *     push entry into worklist
    *
    * ------------------------------------------------------------
    * Step 2: Process nodes until the worklist becomes empty
    *   While worklist is not empty:
    *
    *     (A) Pop one node n from the front
    *     (B) Mark n as visited
    *
    * ------------------------------------------------------------
    * Step 3: Recompute IN[n]
    *   IN[n] is the union of OUT[p] for all predecessor nodes p.
    *
    *   Pseudocode:
    *     newIN = {}
    *     for each incoming edge (p -> n):
    *         newIN = newIN union OUT[p]
    *
    *   Then store:
    *     IN[n] = newIN
    *
    * ------------------------------------------------------------
    * Step 4: Recompute OUT[n]
    *   Use the standard forward reaching-definitions transfer function:
    *
    *     OUT[n] = GEN[n] union (IN[n] - KILL[n])
    *
    *   Pseudocode:
    *     inMinusKill = getMinus(newIN, KILL[n])
    *     newOUT = GEN[n]
    *     newOUT = newOUT union inMinusKill
    *
    *   Then store:
    *     OUT[n] = newOUT
    *
    * ------------------------------------------------------------
    * Step 5: Decide whether successors should be revisited
    *   For each successor s of node n:
    *
    *     push s into the worklist if:
    *       - OUT[n] changed, OR
    *       - s has not been visited yet
    *
    *   This ensures:
    *     - new reaching-definition information keeps propagating
    *     - every reachable node is processed at least once
    *
    * ------------------------------------------------------------
    * Step 6: Continue until convergence
    *   The loop terminates when the worklist is empty.
    *   At that point, IN and OUT have reached a fixpoint
    *   for this CFG.
    *
    * ------------------------------------------------------------
    * Step 7: Build the DFG using the final IN facts
    *   After the DFA converges:
    *
    *     buildDFG(cfg, IN)
    *
    *   Meaning:
    *     for each use at a node, connect it to the reaching
    *     definition nodes recorded in IN.
    *
    * ------------------------------------------------------------
    * Output of this function:
    *   - Computes final IN/OUT reaching-definition facts
    *   - Builds intra-procedural DFG edges based on those facts
    *
    * Common mistakes to avoid:
    *   - Forgetting that IN, OUT, GEN, and KILL are DFASet
    *   - Not taking the union of all predecessor OUT sets
    *   - Mixing up the transfer function:
    *       OUT[n] = GEN[n] union (IN[n] - KILL[n])
    *   - Forgetting to process unvisited successors
    *   - Building the DFG before the worklist iteration finishes
    *
    * Important note:
    *   If you want to test whether OUT[n] changed, compare newOUT
    *   with the old OUT[n] BEFORE writing:
    *       OUT[n] = newOUT
    *   Otherwise, the comparison will always say "not changed".
    */
    inline void performDFA(CFG *cfg) 
    {
        
    }

    // implicit def
    inline void handleStore(llvm::Instruction* inst, ValueSet& defs) 
    {
        llvm::StoreInst *SI = llvm::dyn_cast<llvm::StoreInst>(inst);
        PTS pts = pta->getPTS (SI->getPointerOperand());
        for (auto it = pts.begin (); it != pts.end (); it++)
        {
            PAGNode* pagNode = *it;
            defs.insert (pagNode->value);
        }

        return;
    }

    inline ValueSet getDefinitions(DFGNode* node) 
    {
        ValueSet defs, uses;
        llvm::Instruction* inst = node->getInstruction ();

        // Special handling: Entry node defines function arguments
        if (node->isEntry())
        {
            llvm::Function* function = ((CFGEntryNode*)node)->getFunction();
            for (llvm::Argument &arg : function->args())
            {
                defs.insert(&arg);

                auto& nodeSet = defToNode[&arg];
                nodeSet.insert (node);
            }
            return defs;
        }
        else if (node->isExit() || inst == nullptr)
        {
            return defs;
        }
        else if (llvmParser->isStore (inst))
        { 
            //imoplicit defition
            handleStore (inst, defs);
        }
        else
        {
            // explicit definition
            llvmParser->getDefUse (inst, defs, uses);
        }

        // update def to node mapping
        for (auto def : defs)
        {
            auto& nodeSet = defToNode[def];
            nodeSet.insert (node);
        }

        return defs;
    }

    // implicit use
    inline void handleLoad(llvm::Instruction* inst, ValueSet& uses) 
    {
        auto *loadInst = llvm::dyn_cast<llvm::LoadInst>(inst);
        PTS pts = pta->getPTS (loadInst->getPointerOperand());
        for (auto it = pts.begin (); it != pts.end (); it++)
        {
            PAGNode* pagNode = *it;
            uses.insert (pagNode->value);
        }

        return;
    }

    inline ValueSet getUses(DFGNode* node) 
    {
        ValueSet defs, uses;
        llvm::Instruction* inst = node->getInstruction ();
        if (inst == nullptr) return uses;

        if (llvmParser->isLoad (inst))
        { 
            //imoplicit defition
            handleLoad (inst, uses);
        }
        else
        {
            llvmParser->getDefUse (inst, defs, uses);
        }
     
        return uses;
    }

    inline ValueSet getMinus (ValueSet& src, ValueSet& oprand)
    {
        ValueSet diff;
        set_difference(src.begin(), src.end(),
                       oprand.begin(), oprand.end(),
                       inserter(diff, diff.begin()));
        return diff;
    }

    inline void addDFGEdge (CFG *cfg, DFGNode* defNode, DFGNode* useNode, llvm::Value* def)
    {
        DFGEdge* edge = cfg->getEdge(defNode, useNode);
        if (edge == NULL)
        {
            edge = new DFGEdge(defNode, useNode);
            assert (edge != NULL);
            cfg->addEdge(edge);
            edge->edgeType = EDGE_DFG;
        }
        else
        {
            edge->edgeType |= EDGE_DFG;
        }
        edge->values.insert (def);
        
        return;
    }


    inline void buildDFG(CFG *cfg, DFASet& IN) 
    {
        // Iterate over all CFG nodes
        for (auto itNode = cfg->begin(); itNode != cfg->end(); ++itNode) 
        {
            DFGNode* node = itNode->second;
            ValueSet uses = getUses(node);

            if (uses.empty())
            {
                continue;
            }

            for (llvm::Value* use : uses)
            {
                // only values whose defs reach this node
                if (IN[node].count(use) == 0)
                {
                    continue;
                }

                auto mapIt = defToNode.find(use);
                if (mapIt == defToNode.end())
                {
                    continue;
                }

                for (DFGNode* defNode : mapIt->second)
                {
                    addDFGEdge(cfg, defNode, node, use);
                }
            }
        }
    }

    inline void showDFASet (string name, ValueSet& vs)
    {
        llvm::errs()<<"\n>>ValueSet: "<<name<<":";
        for (auto value : vs)
        {
            llvm::errs()<<"\n\t"<<*value;
        }
        llvm::errs()<<"\n";
    }

    inline void handleCall (CFG* callerCFG, llvm::CallBase* call, llvm::Function* callee)
    {
        CFG* calleeCFG = icfg->getCFG(callee);
        DFGNode* entryNode = calleeCFG->getEntryNode();

        // Match actual -> formal
        auto actualArgs = call->args();
        auto formalArgs = callee->args();
        auto formalIt = formalArgs.begin();

        for (unsigned i = 0; i < call->arg_size() && formalIt != formalArgs.end(); ++i, ++formalIt)
        {
            llvm::Value* actual = call->getArgOperand(i);
            llvm::Argument* formal = &(*formalIt);

            // Add edge: actual def (from call site) -> formal def (in callee entry)
            auto nodeSet = defToNode[actual];
            for (auto defIt = nodeSet.begin (); defIt != nodeSet.end(); defIt++)
            {
                DFGNode* defNode = *defIt;
                addDFGEdge(callerCFG, defNode, entryNode, formal);
            }
        }
        return;
    }

    inline void handleRet (DFGNode* callNode, llvm::CallBase* call, llvm::Function* callee)
    {
        if (call->getType()->isVoidTy())
        {
            return;
        }
        
        CFG* calleeCFG = icfg->getCFG(callee);
        for (auto calleeNodeIt = calleeCFG->begin(); calleeNodeIt != calleeCFG->end(); ++calleeNodeIt)
        {
            DFGNode* retNode = calleeNodeIt->second;
            llvm::Instruction* retInst = retNode->getInstruction();
            if (!retInst || !llvm::isa<llvm::ReturnInst>(retInst))
                continue;

            llvm::ReturnInst* ret = llvm::cast<llvm::ReturnInst>(retInst);
            llvm::Value* retVal = ret->getReturnValue();
            if (!retVal) continue;

            auto nodeSet = defToNode[retVal];
            for (auto defIt = nodeSet.begin (); defIt != nodeSet.end(); defIt++)
            {
                DFGNode* defNode = *defIt;
                addDFGEdge(calleeCFG, defNode, callNode, retVal);
            }
        }
    }

    inline set<llvm::Function*> resolveCallees(llvm::CallBase* call) 
    {
        set<llvm::Function*> callees;

        if (llvm::Function* direct = call->getCalledFunction()) 
        {
            if (!direct->isDeclaration())
            {
                callees.insert(direct);
            }         
        } 
        else 
        {
            llvm::Value* calledVal = call->getCalledOperand()->stripPointerCasts();        
            PTS pts = pta->getPTS (calledVal);
            for (auto it = pts.begin (); it != pts.end (); it++)
            {
                PAGNode* pagNode = *it;
                if (llvm::Function* func = llvm::dyn_cast<llvm::Function>(pagNode->value)) 
                {
                    if (!func->isDeclaration())
                    {
                        callees.insert(func);
                    }         
                }
            }
        }

        return callees;
    }

    inline void buildIDFG()  
    {
        for (auto itr = icfg->cfg_begin(); itr != icfg->cfg_end(); itr++)
        {
            CFG* callerCFG = itr->second;

            for (auto itNode = callerCFG->begin(); itNode != callerCFG->end(); itNode++)
            {
                DFGNode* callNode = itNode->second;
                llvm::Instruction* inst = callNode->getInstruction();

                if (!inst || !llvm::isa<llvm::CallBase>(inst))
                {
                    continue;
                }    

                llvm::CallBase* call = llvm::cast<llvm::CallBase>(inst);
                std::set<llvm::Function*> callees = resolveCallees(call);

                for (llvm::Function* callee : callees)
                {
                    if (!callee || callee->isDeclaration())
                    {
                        continue;
                    }

                    handleCall (callerCFG, call, callee);
                    handleRet (callNode, call, callee);                    
                }
            }
        }
    }
};

class DFGVisual : public GraphVis<DFGNode, DFGEdge, DFG> 
{
public:
    DFGVisual(const string& graphName, DFG* graph)
        : GraphVis<DFGNode, DFGEdge, DFG>(graphName, graph) {}

    ~DFGVisual() = default;

    inline string getNodeLabel (CFGNode *node)
    {
        if (node->isEntry ())
        {
            CFGEntryNode* enNode = (CFGEntryNode*)node;
            llvm::Function* func = enNode->getFunction ();
            string label = LLVM().getValueLabel (func);
            label += "( ";
            for (llvm::Argument &arg : func->args())
            {
                label += LLVM().getValueLabel (&arg) + " ";
            }
            label += ")";

            return label;
        }
        else if (node->isExit ())
        {
            return "exit";
        }
        else
        {
            llvm::Instruction* inst = node->getInstruction ();
            std::string instStr = LLVM().getValueLabel (inst);
            return escapeForDotLabel (instStr);
        }
    }

    inline void writeCFGNodes (CFG *cfg)
    {
        for (auto it = cfg->begin (), end = cfg->end (); it != end; it++)
        {
            CFGNode *node = it->second;
            if (!IsVizNode (node))
            {
                continue;
            }
            writeNodes (node);
        }
    }

    inline void writeEdge(CFGEdge *edge) 
    {
        string str;

        /* NodeId -> NodeId[style=solid,color=black, ,label="..."]; */
        if (edge->edgeType&EDGE_CFG)
        {
            str = "\t" + getNodeName (edge->getSrcNode()) + " -> " + getNodeName (edge->getDstNode()) +
              "[" + getEdgeAttributes (edge) + ",label=\"\"];";
            fprintf(m_File, "%s\n", str.c_str());
        }
        
        if (edge->edgeType&EDGE_DFG)
        {
            str = "\t" + getNodeName (edge->getSrcNode()) + " -> " + getNodeName (edge->getDstNode()) +
              "[color=green,label=\"\"];";
            fprintf(m_File, "%s\n", str.c_str());
        }

        return; 
     
    }

    inline void writeCFGAllEdges (CFG *cfg)
    {
        for (auto it = cfg->begin (), end = cfg->end (); it != end; it++)
        {
            CFGNode *node = it->second;
            if (!IsVizNode (node))
            {
                continue;
            }

            for (auto itEdge = node->outEdgeBegin (), itEnd = node->outEdgeEnd (); itEdge != itEnd; itEdge++)
            {
                CFGEdge *edge = *itEdge;
                if (!IsVizNode (edge->getDstNode()))
                {
                    continue;
                }
                
                writeEdge (edge);
            }
        }
    }

    void writeGraph () 
    {
        writeHeader(m_GraphName);

        // write nodes
        fprintf(m_File, "\t// Define the nodes\n");
        ICFG* icfg = m_Graph->getICFG();
        for (auto it = icfg->cfg_begin (), end = icfg->cfg_end (); it != end; it++)
        {
            CFG *cfg = it->second;
            writeCFGNodes (cfg);
        }
        //writeAllNodes (m_Graph);
        fprintf(m_File, "\n\n");

        // write edges
        fprintf(m_File, "\t// Define the edges\n"); 
        for (auto it = icfg->cfg_begin (), end = icfg->cfg_end (); it != end; it++)
        {
            CFG *cfg = it->second;
            writeCFGAllEdges (cfg);
        }
        //writeAllEdges (m_Graph);
        fprintf(m_File, "}\n");
    }

    inline string getNodeAttributes(CFGNode *node) 
    {
        string str = "shape=rectangle, color=black";   
        return str;
    }  
};


#endif // _DFG_H_
